### PR TITLE
Feat/c search notes

### PR DESCRIPTION
**Pull request by alykhan02**
# Description

**Summary of Changes:** 
Incorporate a Note Search feature that allows users to find notes by title

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update
- [ ] Chore (anything else)

## How Has This Been Tested?

- [x] Responsiveness on various devices
- Desktop Browser
  - [x] Apple Safari
  - [x] Google Chrome
  - [x] Microsoft Edge
  - [x] Mozilla FireFox
- Mobile Browser
  - [x] Apple Safari
  - [x] Google Chrome
  - [x] Microsoft Edge
  - [x] Mozilla FireFox
- Other Tests:

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## PR Closure

- Use **Squash And Merge** to Close Pull Request
- Delete any branch after merging

### CODE REVIEW

**Comment by CarterMorris** [comment]
lgtm

**Review by EkVid — APPROVED** [review]
LGTM

**Review by auricz — APPROVED** [review]
is gud

**Review by CarterMorris — COMMENTED** [review]
fire

**Pull request merged**
