### PR TITLE
Feat/a colour coding

### PR DESCRIPTION
**Pull request by EkVid**
# Description

Summary of Changes: 

Develop a color coding feature for notes. It allows users to assign a color to a note
for better organization and visual categorization. 

## Type of change

- [] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update
- [ ] Chore (anything else)

## How Has This Been Tested?

- [x] Responsiveness on various devices
- Desktop Browser
  - [x] Apple Safari
  - [x] Google Chrome
  - [ ] Microsoft Edge
  - [ ] Mozilla FireFox
- Mobile Browser
  - [x] Apple Safari
  - [x] Google Chrome
  - [ ] Microsoft Edge
  - [ ] Mozilla FireFox
- Other Tests:

## Checklist

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## PR Closure

- Use **Squash And Merge** to Close Pull Request
- Delete any branch after merging

### CODE REVIEW

**Review by CarterMorris — COMMENTED** [review]
yuh

**Review by auricz — APPROVED** [review]
K, is gud

**Review by ali-rajan — APPROVED** [review]
LGTM

**Review by alykhan02 — APPROVED** [review]
lgtm

**Review by ali-rajan — COMMENTED** [review]
lgtm

**Pull request merged**
